version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - aws sts get-caller-identity
      - echo "Installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.8.2/terraform_1.8.2_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform -version


  pre_build:
    commands:
      - chmod +x *.sh
      - ./validate.sh && ./ips.sh && ./create_users.sh

  build:
    commands:
      - echo "Setting up Terraform backend (if any)..."
      - terraform init -input=false
      - echo "Planning Terraform changes..."
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo "Applying Terraform changes..."
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - '**/*'
